n = int(input('Informe um numero: ')) .strip()
print('Analisando o numero {}'.format(n))
n = int(n.zfill(4))
print('Unidade: {}'.format(n[3]))
print('Dezena: {}'.format(n[2]))
print('Centena: {}'.format(n[1]))
print('Milhar: {}'.format(n[0]))
